// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Setup = require("./setup");

var lambda = Setup.setupLambda();

var server = lambda.graphqlHandler;

var playground = lambda.playgroundHandler;

exports.lambda = lambda;
exports.server = server;
exports.playground = playground;
/* lambda Not a pure module */
